# Generated by Django 3.2.9 on 2024-05-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupondirection',
            name='coupon',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='to_direction', to='coupon.coupon', verbose_name='优惠劵'),
        ),
    ]
